server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mvecommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: change-me-please
    expiration: 86400000 # 1d in ms
  payment:
    provider: stripe # or razorpay
